name: Deploy Buku Tamu User BMKG FE

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Checkout repository
      # -----------------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # -----------------------------
      # Login ke Docker Hub
      # -----------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------------
      # Build Docker image
      # -----------------------------
      - name: Build Docker image
        run: |
          docker build -t bhinnekadev/buku-tamu-user:dev .

      # -----------------------------
      # Push Docker image
      # -----------------------------
      - name: Push Docker image
        run: |
          docker push bhinnekadev/buku-tamu-user:dev

      # -----------------------------
      # Setup SSH ke server
      # -----------------------------
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts || true

      # -----------------------------
      # Deploy ke server (stable)
      # -----------------------------
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}

            echo "Stopping old containers..."
            docker compose down || true

            echo "Removing old image..."
            docker rmi -f bhinnekadev/buku-tamu-user:dev || true

            echo "Pulling latest image..."
            docker pull bhinnekadev/buku-tamu-user:dev

            echo "Starting new containers..."
            docker compose up -d --force-recreate

            echo "Deploy finished! Containers are running:"
            docker ps
          EOF